# Generated by Django 3.2.5 on 2021-07-24 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financetracker', '0002_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время'),
        ),
    ]
