# Generated by Django 3.2.5 on 2021-07-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financetracker', '0004_alter_finance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Заголовок'),
        ),
    ]
